version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=api-restful
        ports:
            - "5432:5432"
        volumes:
            - ~/postgres:/var/lib/postgresql/data
        restart: always
